"""Add gender and region to Profile

Revision ID: 0f93afabe689
Revises: 34d6368412da
Create Date: 2026-06-08 22:05:22.667160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f93afabe689'
down_revision: Union[str, Sequence[str], None] = '34d6368412da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'region')
    op.drop_column('profile', 'gender')
    # ### end Alembic commands ###
