"""Update models for Figma design

Revision ID: de029ae14a2a
Revises: 0f93afabe689
Create Date: 2026-06-08 22:45:06.647094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de029ae14a2a'
down_revision: Union[str, Sequence[str], None] = '0f93afabe689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('hero_image_url', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('field_visibility', sa.JSON(), nullable=True))
    op.add_column('profile', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.drop_column('profile', 'age_range')
    op.add_column('work_credits', sa.Column('role_weight', sa.String(), nullable=True))
    op.add_column('work_credits', sa.Column('character_name', sa.String(), nullable=True))
    op.add_column('works', sa.Column('work_type', sa.String(), nullable=True))
    op.add_column('works', sa.Column('poster_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'poster_image_url')
    op.drop_column('works', 'work_type')
    op.drop_column('work_credits', 'character_name')
    op.drop_column('work_credits', 'role_weight')
    op.add_column('profile', sa.Column('age_range', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile', 'is_premium')
    op.drop_column('profile', 'field_visibility')
    op.drop_column('profile', 'birth_year')
    op.drop_column('profile', 'hero_image_url')
    # ### end Alembic commands ###
